 // Source code is unavailable, and was generated by the Fernflower decompiler.
package gestion_recursos.servicios_informaticos;

import comun.BD;
import comun.e138;
import java.sql.ResultSet;

public class zolicitud_zer {
   public String problema = "";
   public String fecha_registro = "";
   public String kategorizazion = "";
   public String zoluzion = "";
   public String fecha_termino = "";
   public String fecha_evaluazion;
   public int cve_zolizitante = 0;
   public int folio = 0;
   public int anio = 0;
   public int cve_perzona_zoporte = 0;
   public int kalifikazion = 0;
   public int cve_bien = 0;
   public int kalifikazion_tiempo = 0;
   public int kalifikazion_amabilidad = 0;
   public String error = "";
   public String consultas = "";
   public String fecha_azignazion = "";
   public String num_inventario = "";
   public String fecha_kanzelazion = "";
   public String motivo_kanzelazion = "";
   public String mensaje = "";
   public String comentario_evaluacion = "";
   public String comentario_kalifikazion = "";
   public String comentario_kalifikazion_tiempo = "";
   public String comentario_kalifikazion_amabilidad = "";
   public int cve_usuario_gral = 0;
   // Campos añadidos para soportar notificación por correo en reasignación
   public String mensaje_a = "";
   public String strCorreoPersonalSoporte = "";
   public String solSolicitante = "";
   public String solProblema = "";
   public String solFechaRegistro = "";
   ResultSet rs;
   BD SMBD;
   e138 aaa;
   e138 e;
   public int intCvePersonaEvalua = 0;

   public zolicitud_zer() {
      try {
         this.SMBD = new BD();
         this.aaa = new e138();
         this.e = new e138();
      } catch (Exception ex) {
         this.error = (ex.getMessage() == null) ? "Error inicializando zolicitud_zer" : ex.getMessage();
         throw new RuntimeException(ex);
      }
   }

   public void registro_zolizitud() throws Exception {
      this.consultas = "SELECT DATEPART(YY,GETDATE()) AS maximo FROM personal WHERE (cve_persona = 97) ";
      this.anio = this.SMBD.buscaSQL(this.consultas);
      this.consultas = "SELECT MAX(cve_zol) AS maximo FROM zolizitudez_trabajo WHERE (anio = " + this.anio + ")";
      this.folio = this.SMBD.buscaSQL(this.consultas) + 1;
      this.consultas = "INSERT INTO zolizitudez_trabajo (cve_zol, anio, cve_zolizitante, problema, fecha_regiztro, fecha_azignazion, kategorizazion,cve_perzona_zoporte, zoluzion, fecha_termino, fecha_evaluazion, kalifikazion, num_inventario, cve_bien, fecha_kanzelazion, motivo_kanzelazion,kalifikazion_tiempo, kalifikazion_amabilidad, comentario_evaluacion) VALUES (" + this.folio + "," + this.anio + "," + this.cve_zolizitante + ",'" + this.problema + "', GETDATE()," + "null,'---',0,'',null,null,0,'" + this.num_inventario + "',0, null, ''," + "0,0,'') ";
      this.SMBD.insertarSQL(this.consultas);
      if (this.num_inventario.length() > 4) {
         this.consultas = "SELECT cve_bien AS maximo FROM alta_activo_fijo WHERE (num_inven LIKE '%" + this.num_inventario + "%') ";
         this.cve_bien = this.SMBD.buscaSQL(this.consultas);
         if (this.cve_bien > 0) {
            this.consultas = "UPDATE zolizitudez_trabajo SET cve_bien = " + this.cve_bien + " " + "WHERE (cve_zol = " + this.folio + ") AND (anio = " + this.anio + ") ";
            this.SMBD.insertarSQL(this.consultas);
         }
      }

      this.aaa.encabezado = "Notification System (Solicitudes de trabajo)";
      this.mensaje = "ESTIMADO COMPA\u00d1ERO, HA RECIBIDO UN MENSAJE DE NOTIFICACION DEL USUARIO " + this.SMBD.nombre_persona(this.cve_usuario_gral) + ", " + "PARA LA ATENCI\u00d3N DE LA SOLICITUD DE TRABAJO : " + this.folio + " / " + this.anio + " " + "\n " + "\n " + "FAVOR DE INGRESAR AL SIISC (SOLICITUDES DE TRABAJO) " + "\n " + "\n " + "\n" + "ATENTAMENTE \n" + "SISTEMA INTEGRAL DE INFORMACION DEL SISTEMA DE CALIDAD \n" + "DEPARTAMENTO DE TECNOLOGIAS DE LA INFORMACION";
      this.aaa.envio_general(74, this.mensaje);
   }

   public void actualiza_zolizitud() throws Exception {
      this.consultas = "UPDATE zolizitudez_trabajo SET problema = '" + this.problema + "' " + "WHERE (cve_zol = " + this.folio + ") AND (anio = " + this.anio + ") AND (fecha_azignazion IS NULL) AND (fecha_kanzelazion IS NULL)";
      this.SMBD.insertarSQL(this.consultas);
   }

   public void buska_zolizitud() throws Exception {
      this.consultas = "SELECT problema, fecha_regiztro, fecha_azignazion, kategorizazion, cve_perzona_zoporte, zoluzion, fecha_termino, fecha_evaluazion, kalifikazion, num_inventario FROM zolizitudez_trabajo WHERE (cve_zol = " + this.folio + ") AND (anio = " + this.anio + ") ";

      for(this.rs = this.SMBD.SQLBD(this.consultas); this.rs.next(); this.fecha_registro = this.fecha_registro.substring(0, 10)) {
         this.problema = this.rs.getString(1);
         this.fecha_registro = this.rs.getString(2);
         this.fecha_azignazion = this.rs.getString(3);
         this.kategorizazion = this.rs.getString(4);
         this.cve_perzona_zoporte = this.rs.getInt(5);
         this.zoluzion = this.rs.getString(6);
         this.fecha_termino = this.rs.getString(7);
         this.fecha_evaluazion = this.rs.getString(8);
         this.kalifikazion = this.rs.getInt(9);
         this.num_inventario = this.rs.getString(10);
      }

      this.SMBD.desconectarBD();
      if (this.fecha_azignazion != null) {
         this.fecha_azignazion = this.fecha_azignazion.substring(0, 10);
      }

      if (this.fecha_termino != null) {
         this.fecha_termino = this.fecha_termino.substring(0, 10);
      }

      if (this.fecha_evaluazion != null) {
         this.fecha_evaluazion = this.fecha_evaluazion.substring(0, 10);
      }

   }

   public void azignazion_zolizitud() throws Exception {
      this.consultas = "UPDATE zolizitudez_trabajo SET fecha_azignazion = GETDATE(), cve_perzona_zoporte = " + this.cve_perzona_zoporte + " " + "WHERE (cve_zol = " + this.folio + ") AND (anio = " + this.anio + ") AND (fecha_azignazion IS NULL) AND (fecha_kanzelazion IS NULL)";
      this.SMBD.insertarSQL(this.consultas);
      this.aaa.encabezado = "Notification System (Solicitudes de trabajo - Atenci\u00f3n)";
      this.mensaje = "ESTIMADO COMPA\u00d1ERO, HA RECIBIDO UN MENSAJE DE NOTIFICACION DEL USUARIO " + this.SMBD.nombre_persona(this.cve_usuario_gral) + ", " + "PARA LA ATENCI\u00d3N DE LA SOLICITUD DE TRABAJO : " + this.folio + " / " + this.anio + " " + "\n " + "\n " + "FAVOR DE INGRESAR AL SIISC (SOLICITUDES DE TRABAJO) " + "\n " + "\n " + "\n" + "ATENTAMENTE \n" + "SISTEMA INTEGRAL DE INFORMACION DEL SISTEMA DE CALIDAD \n" + "DEPARTAMENTO DE TECNOLOGIAS DE LA INFORMACION";
      this.aaa.envio_general(this.cve_perzona_zoporte, this.mensaje);
   }

   public void reazignazion_zolizitud() throws Exception {
      this.consultas = "UPDATE zolizitudez_trabajo SET cve_perzona_zoporte = " + this.cve_perzona_zoporte + " " +
         "WHERE (cve_zol = " + this.folio + ") AND (anio = " + this.anio + ") AND (fecha_kanzelazion IS NULL) AND (fecha_azignazion IS NOT NULL) AND (fecha_evaluazion IS NULL)";
      this.SMBD.insertarSQL(this.consultas);
   }
   
     

   

   public void regiztro_kategorizazion() throws Exception {
      this.consultas = "UPDATE zolizitudez_trabajo SET kategorizazion = '" + this.kategorizazion + "' " + "WHERE (cve_zol = " + this.folio + ") AND (anio = " + this.anio + ") AND (fecha_evaluazion IS NULL) AND (fecha_kanzelazion IS NULL)";
      this.SMBD.insertarSQL(this.consultas);
   }

   public void regiztro_zoluzion() throws Exception {
      this.consultas = "UPDATE zolizitudez_trabajo SET zoluzion = '" + this.zoluzion + "' " + "WHERE (cve_zol = " + this.folio + ") AND (anio = " + this.anio + ") AND (fecha_evaluazion IS NULL) AND (fecha_kanzelazion IS NULL) ";
      this.SMBD.insertarSQL(this.consultas);
      this.consultas = "SELECT cve_zolizitante AS maximo FROM zolizitudez_trabajo WHERE (cve_zol = " + this.folio + ") AND (anio = " + this.anio + ") ";
      this.cve_zolizitante = this.SMBD.buscaSQL(this.consultas);
      this.aaa.encabezado = "Notification System (Solicitudes de trabajo - Seguimiento)";
      this.mensaje = "ESTIMADO COMPA\u00d1ERO, HA RECIBIDO UN MENSAJE DE NOTIFICACION DEL USUARIO " + this.SMBD.nombre_persona(this.cve_usuario_gral) + ", " + "INFORMANDOTE SOBRE LA SOLUCI\u00d3N QUE SE LE HA DADO A TU SOLICITUD DE TRABAJO : " + this.folio + " / " + this.anio + " " + "\n " + "\n " + "FAVOR DE INGRESAR AL SIISC (SOLICITUDES DE TRABAJO) Y REVISAR SI YA SE CORRIGIO EL PROBLEMA. " + "\n " + "\n " + "\n" + "ATENTAMENTE \n" + "SISTEMA INTEGRAL DE INFORMACION DEL SISTEMA DE CALIDAD \n" + "DEPARTAMENTO DE TECNOLOGIAS DE LA INFORMACION";
      this.aaa.envio_general(this.cve_zolizitante, this.mensaje);
   }

   public void concluir_zolizitud_trabajo() throws Exception {
      this.consultas = "UPDATE zolizitudez_trabajo SET fecha_termino = " + this.SMBD.fecha_convertida(this.fecha_termino) + ", " + " cve_persona_evalua = " + this.intCvePersonaEvalua + " WHERE cve_zol = " + this.folio + " AND anio = " + this.anio + " AND fecha_evaluazion IS NULL " + " AND fecha_kanzelazion IS NULL";
      this.SMBD.insertarSQL(this.consultas);
      this.consultas = "SELECT cve_zolizitante AS maximo FROM zolizitudez_trabajo WHERE (cve_zol = " + this.folio + ") AND (anio = " + this.anio + ") ";
      this.cve_zolizitante = this.SMBD.buscaSQL(this.consultas);
   }

   public void actualizar_persona_evalua() throws Exception {
      this.consultas = "UPDATE zolizitudez_trabajo SET cve_persona_evalua = " + this.intCvePersonaEvalua + " WHERE cve_zol = " + this.folio + " AND anio = " + this.anio;
      this.SMBD.insertarSQL(this.consultas);
   }

   public void kanzelar_zolizitudtrabajo() throws Exception {
      this.consultas = "UPDATE zolizitudez_trabajo SET fecha_kanzelazion = " + this.SMBD.fecha_convertida(this.fecha_kanzelazion) + ", " + "motivo_kanzelazion = '" + this.motivo_kanzelazion + "' " + "WHERE (cve_zol = " + this.folio + ") AND (anio = " + this.anio + ") AND (fecha_kanzelazion IS NULL) ";
      this.SMBD.insertarSQL(this.consultas);
      this.consultas = "SELECT cve_zolizitante AS maximo FROM zolizitudez_trabajo WHERE (cve_zol = " + this.folio + ") AND (anio = " + this.anio + ") ";
      this.cve_zolizitante = this.SMBD.buscaSQL(this.consultas);
      this.aaa.encabezado = "Notification System (Solicitudes de trabajo - Cancelaci\u00f3n)";
      this.mensaje = "ESTIMADO COMPA\u00d1ERO, HAS RECIBIDO UN MENSAJE DE NOTIFICACION DEL USUARIO " + this.SMBD.nombre_persona(this.cve_usuario_gral) + ", " + "INFORMANDOTE QUE SE HA CANCELADO TU SOLICITUD DE TRABAJO : " + this.folio + " / " + this.anio + " " + "\n " + "\n " + "LA RAZON ES : " + this.motivo_kanzelazion + " " + "\n " + "\n" + "ATENTAMENTE \n" + "SISTEMA INTEGRAL DE INFORMACION DEL SISTEMA DE CALIDAD \n" + "DEPARTAMENTO DE TECNOLOGIAS DE LA INFORMACION";
      this.aaa.envio_general(this.cve_zolizitante, this.mensaje);
   }

   public void actualiza_num_inventario() throws Exception {
      this.consultas = "UPDATE zolizitudez_trabajo SET num_inventario = '" + this.num_inventario + "' " + "WHERE (cve_zol = " + this.folio + ") AND (anio = " + this.anio + ") AND (fecha_kanzelazion IS NULL) ";
      this.SMBD.insertarSQL(this.consultas);
      this.consultas = "SELECT cve_bien AS maximo FROM alta_activo_fijo WHERE (num_inven LIKE '%" + this.num_inventario + "%') ";
      this.cve_bien = this.SMBD.buscaSQL(this.consultas);
      if (this.cve_bien > 0) {
         this.consultas = "UPDATE zolizitudez_trabajo SET cve_bien = " + this.cve_bien + " " + "WHERE (cve_zol = " + this.folio + ") AND (anio = " + this.anio + ") ";
         this.SMBD.insertarSQL(this.consultas);
      }

   }

   public void kalifikar_zolizitud_trabajo() throws Exception {
      String ck  = (this.comentario_kalifikazion == null) ? "" : this.comentario_kalifikazion.replace("'", "''");
      String ckt = (this.comentario_kalifikazion_tiempo == null) ? "" : this.comentario_kalifikazion_tiempo.replace("'", "''");
      String cka = (this.comentario_kalifikazion_amabilidad == null) ? "" : this.comentario_kalifikazion_amabilidad.replace("'", "''");
      String ce  = (this.comentario_evaluacion == null) ? "" : this.comentario_evaluacion.replace("'", "''");

      this.consultas =
         "UPDATE zolizitudez_trabajo SET " +
         "kalifikazion = " + this.kalifikazion + ", " +
         "kalifikazion_tiempo = " + this.kalifikazion_tiempo + ", " +
         "kalifikazion_amabilidad = " + this.kalifikazion_amabilidad + ", " +
         "comentario_kalifikazion = '" + ck + "', " +
         "comentario_kalifikazion_tiempo = '" + ckt + "', " +
         "comentario_kalifikazion_amabilidad = '" + cka + "', " +
         "comentario_evaluacion = '" + ce + "', " +
         "fecha_evaluazion = GETDATE() " +
         "WHERE (cve_zol = " + this.folio + ") AND (anio = " + this.anio + ") AND (fecha_kanzelazion IS NULL) ";
      this.SMBD.insertarSQL(this.consultas);
   }

   public void notificar_nuevamente() throws Exception {
      this.consultas = "SELECT  zolizitudez_trabajo.cve_zol, zolizitudez_trabajo.anio, zolizitudez_trabajo.cve_zolizitante, zolizitudez_trabajo.cve_perzona_zoporte, zolizitudez_trabajo.problema FROM  zolizitudez_trabajo WHERE  (zolizitudez_trabajo.fecha_kanzelazion IS NULL) AND (zolizitudez_trabajo.fecha_termino IS NOT NULL) AND (zolizitudez_trabajo.fecha_azignazion IS NOT NULL) AND (zolizitudez_trabajo.fecha_evaluazion IS NULL) ORDER BY zolizitudez_trabajo.cve_perzona_zoporte ";
      this.rs = this.SMBD.SQLBD(this.consultas);

      while(this.rs.next()) {
         this.folio = this.rs.getInt(1);
         this.anio = this.rs.getInt(2);
         this.cve_zolizitante = this.rs.getInt(3);
         this.cve_usuario_gral = this.rs.getInt(4);
         this.motivo_kanzelazion = this.rs.getString(5);
         this.aaa.encabezado = "Notification System (Solicitudes de trabajo - Evaluaci\u00f3n)";
         this.mensaje = "ESTIMADO COMPA\u00d1ERO, HAS RECIBIDO UN MENSAJE DE NOTIFICACION DEL USUARIO " + this.SMBD.nombre_persona(this.cve_usuario_gral) + ", " + "INFORMANDOTE QUE SE HA ATENDIDO TU SOLICITUD DE TRABAJO : " + this.folio + " / " + this.anio + " " + "\n " + "\n " + "PROBLEMA REPORTADO : " + this.motivo_kanzelazion + " \n \n " + "FAVOR DE EVALUAR LA SOLICITUD DE TRABAJO EN EL M\u00d3DULO: " + "\n " + "\n " + " GESTION DE LOS RECURSOS / SERVICIOS INFORM\u00c1TICOS / SOLICITUD DE TRABAJO INFORMATICO " + "\n" + "\n" + "ATENTAMENTE \n" + "SISTEMA INTEGRAL DE INFORMACION DEL SISTEMA DE CALIDAD \n" + "DEPARTAMENTO DE TECNOLOGIAS DE LA INFORMACION";
         this.aaa.envio_general(this.cve_zolizitante, this.mensaje);
      }

      this.SMBD.desconectarBD();
   }

   public static void main(String[] arg) throws Exception {
      new zolicitud_zer();
      System.out.println("NAL -- 10/12/2015  -- Se agrego funcion actualizar_persona_evalua y en la funcion de terminar sol se agrego actualiza campo de persona que evalua");
      System.out.println("NAL -- 21/11/2025  -- Se modifico la funcion reazignazion_zolizitud"); 
   }
}
