 // Source code is unavailable, and was generated by the Fernflower decompiler.
package prestacion_servicio.apoyo.ingles;

import comun.BD;
import comun.e138;
import java.sql.ResultSet;

public class alta_grupos_aca_ingles_nme {
   String StrConsultas;
   public int cve_grupo;
   public int cve_periodo;
   public int cve_profesor;
   public int cve_nivel;
   public int cve_profesor_original;
   public int cve_profesor_comple;
   public int cve_profesor_acciones;
   public int cuantos;
   public int cves_maestros;
   public int cve_regiztra;
   public int grado_academico;
   public int cve_alumno;
   public int cve_materia_academica;
   public int cve_grupo_academica;
   public String periodo;
   public String nombre_grupo;
   public String error;
   public String nombre_profesor;
   public String nombre_nivel;
   public String mensaje;
   public String fecha_ordinaria;
   public String fecha_comple;
   public String fecha_acciones;
   public int puede_modificar_doc;
   public int puede_modificar_doc_original;
   ResultSet rs;
   BD MBD = new BD();
   e138 AGAI = new e138();

   public alta_grupos_aca_ingles_nme() throws Exception {
      this.MBD = new BD();
      this.StrConsultas = "";
      this.cve_grupo = 0;
      this.error = "";
      this.cve_periodo = 0;
      this.cve_nivel = 0;
      this.periodo = "";
      this.nombre_grupo = "";
      this.cve_profesor = 0;
      this.nombre_profesor = "";
      this.nombre_nivel = "";
      this.cuantos = 0;
      this.mensaje = "";
      this.cve_regiztra = 0;
      this.grado_academico = 0;
      this.cve_alumno = 0;
      this.cve_materia_academica = 0;
      this.cve_grupo_academica = 0;
      this.cve_profesor_original = 0;
      this.puede_modificar_doc_original = 0;
      this.puede_modificar_doc = 0;
      this.cve_profesor_comple = 0;
      this.cve_profesor_acciones = 0;
      this.fecha_ordinaria = "";
      this.fecha_comple = "";
      this.fecha_acciones = "";
   }

   public void inserta_grupo_nuevo() throws Exception {
      this.StrConsultas = "SELECT MAX (cve_grupo) AS maximo FROM nme_ai_grupos ";
      this.cve_grupo = this.MBD.buscaSQL(this.StrConsultas) + 1;
      this.StrConsultas = "INSERT INTO ai_grupos (cve_grupo, nombre, cve_maestro, cve_nivel, cve_periodo, fecha_regiztro, cve_kien_regiztro, grado_academico, porc_mez_1_t, porc_mez_2_t, porc_mez_3_t, porc_mez_4_t, porc_mez_1_p, porc_mez_2_p, porc_mez_3_p, porc_mez_4_p, fecha_zierre_mez_1, fecha_zierre_mez_2, fecha_zierre_mez_3, fecha_zierre_mez_4, cve_maestro_comple, cve_maestro_accionez, fecha_firma_ordinaria, fecha_firma_comple, fecha_firma_accionez) VALUES (" + this.cve_grupo + ",'" + this.nombre_grupo + "'," + this.cve_profesor + "," + this.cve_nivel + "," + this.cve_periodo + ", GETDATE(), " + this.cve_regiztra + ", " + this.grado_academico + ", 0, 0, 0, 0, 0, 0, 0, 0, null, null, null, null, " + this.cve_profesor_comple + "," + this.cve_profesor_acciones + ",null, null, null) ";
      this.MBD.insertarSQL(this.StrConsultas);
      this.error = "GRUPO REGISTRADO";
   }

   public void actualiza_grupo() throws Exception {
      this.StrConsultas = "SELECT cve_maestro AS maximo FROM ai_grupos WHERE (cve_grupo = " + this.cve_grupo + ") ";
      this.cve_profesor_original = this.MBD.buscaSQL(this.StrConsultas);
      this.StrConsultas = "SELECT ISNULL( CONVERT(VARCHAR(24), fecha_vb_dir, 103), '__') AS fecha_vb_dir, ISNULL( CONVERT(VARCHAR(24), fecha_vb_rh, 103), '__') AS fecha_vb_rh, ISNULL( CONVERT(VARCHAR(24), fecha_vb_dozente, 103), '__') AS fecha_vb_dozente, ban_vb_dozente FROM  ai_konformazion_orarioz WHERE (cve_maestro = " + this.cve_profesor_original + ") AND (cve_periodo = " + this.cve_periodo + ") ";
      this.puede_modificar_doc_original = 0;
      this.rs = this.MBD.SQLBD(this.StrConsultas);

      while(this.rs.next()) {
         if (this.rs.getString(2).length() > 9) {
            this.puede_modificar_doc_original = 1;
         } else if (this.rs.getString(3).length() > 9) {
            this.puede_modificar_doc_original = 1;
         }
      }

      this.MBD.desconectarBD();
      this.StrConsultas = "SELECT ISNULL( CONVERT(VARCHAR(24), fecha_vb_dir, 103), '__') AS fecha_vb_dir, ISNULL( CONVERT(VARCHAR(24), fecha_vb_rh, 103), '__') AS fecha_vb_rh, ISNULL( CONVERT(VARCHAR(24), fecha_vb_dozente, 103), '__') AS fecha_vb_dozente, ban_vb_dozente FROM  ai_konformazion_orarioz WHERE (cve_maestro = " + this.cve_profesor + ") AND (cve_periodo = " + this.cve_periodo + ") ";
      this.puede_modificar_doc = 0;
      this.rs = this.MBD.SQLBD(this.StrConsultas);

      while(this.rs.next()) {
         if (this.rs.getString(2).length() > 9) {
            this.puede_modificar_doc = 1;
         } else if (this.rs.getString(3).length() > 9) {
            this.puede_modificar_doc = 1;
         }
      }

      this.MBD.desconectarBD();
      if (this.puede_modificar_doc == 0 && this.puede_modificar_doc_original == 0) {
         if (this.cve_profesor_original == this.cve_profesor) {
            this.StrConsultas = "UPDATE ai_grupos SET nombre = '" + this.nombre_grupo + "', cve_maestro = " + this.cve_profesor + ", cve_nivel = " + this.cve_nivel + ", grado_academico = " + this.grado_academico + ", fecha_regiztro = GETDATE(), cve_kien_regiztro = " + this.cve_regiztra + " WHERE (cve_grupo = " + this.cve_grupo + ") ";
            this.MBD.insertarSQL(this.StrConsultas);
            this.error = "ACTUALIZACION DEL GRUPO";
         } else {
            this.StrConsultas = "UPDATE ai_grupos SET nombre = '" + this.nombre_grupo + "', cve_maestro = " + this.cve_profesor + ", cve_nivel = " + this.cve_nivel + ", grado_academico = " + this.grado_academico + ", fecha_regiztro = GETDATE(), cve_kien_regiztro = " + this.cve_regiztra + " WHERE (cve_grupo = " + this.cve_grupo + ") ";
            this.MBD.insertarSQL(this.StrConsultas);
            this.error = "ACTUALIZACION DEL GRUPO";
            this.StrConsultas = "UPDATE ai_horarios_clase SET cve_maestro = " + this.cve_profesor + " WHERE (cve_grupo = " + this.cve_grupo + ")";
            this.MBD.insertarSQL(this.StrConsultas);
            this.error = "ACTUALIZACION DEL GRUPO \nActualizaci\u00f3n horario asignado ";
            this.StrConsultas = "SELECT cve_alumno, cve_materia_academica, cve_grupo_academica FROM ai_inscritos WHERE (cve_grupo = " + this.cve_grupo + ") ";
            this.rs = this.MBD.SQLBD(this.StrConsultas);

            while(this.rs.next()) {
               this.cve_alumno = this.rs.getInt(1);
               this.cve_materia_academica = this.rs.getInt(2);
               this.cve_grupo_academica = this.rs.getInt(3);
               this.StrConsultas = "UPDATE calificacion_parcial SET cve_maestro = " + this.cve_profesor + " WHERE (cve_alumno = " + this.cve_alumno + ") AND (cve_materia = " + this.cve_materia_academica + ") AND (cve_grupo = " + this.cve_grupo_academica + ") ";
               this.MBD.insertarSQL(this.StrConsultas);
            }

            this.MBD.desconectarBD();
            this.error = "ACTUALIZACION DEL GRUPO \nActualizaci\u00f3n horario asignado \nActualizaciones de calificaciones";
            this.StrConsultas = "UPDATE ai_materiaz_planeazion_profezor SET cve_profezor = " + this.cve_profesor + " WHERE (cve_grupo = " + this.cve_grupo + ")";
            this.MBD.insertarSQL(this.StrConsultas);
            this.StrConsultas = "UPDATE ai_materiaz_planeazion_impartizion SET cve_profezor = " + this.cve_profesor + " WHERE (cve_grupo = " + this.cve_grupo + ")";
            this.MBD.insertarSQL(this.StrConsultas);
            this.error = "ACTUALIZACION DEL GRUPO \n\nActualizaci\u00f3n horario asignado \n\nActualizaciones de calificaciones \n\nActualizacion de conformacion de horarios \n\nActualizacion de la planeacion";
            this.AGAI.encabezado = "Actualizacion de grupo de idiomas";
            this.mensaje = "Buen@s dias/tardes estimad@ docente, por medio de la presente se le comunica que se le ha asignado un grupo como parte de la academia de idiomas <br> Nombre del Grupo: " + this.nombre_grupo + " <br> Cuatrimestre: " + this.MBD.nombre_Periodo(this.cve_periodo) + " <br> Para la impartici&oacute;n de clases y dar seguimiento del mismo <br> A T E N T A M E N T E <br> Sistema Integral de la Informaci&oacute;n del Sistema de Calidad <br> Coordinaci&oacute;n de idiomas <br> <i> Departamento de Tecnolog&iacute;as de Informaci&oacute;n </i>";
            this.AGAI.envio_general(this.cve_profesor, this.mensaje);
         }
      } else {
         this.error = "Favor de revisar las cargas horarias, ya estan validadas \n\n por el Docente y/o Recursos Humanos";
      }

      if (this.cve_profesor_comple > 0) {
         this.StrConsultas = "UPDATE ai_grupos SET cve_maestro_comple = " + this.cve_profesor_comple + " WHERE (cve_grupo = " + this.cve_grupo + ") AND (fecha_firma_comple IS NULL) ";
         this.MBD.insertarSQL(this.StrConsultas);
         this.StrConsultas = "UPDATE calificacion_parcial SET calificacion_parcial.cve_maestro = ai_grupos.cve_maestro_comple FROM  calificacion_parcial INNER JOIN ai_inscritos ON calificacion_parcial.cve_alumno = ai_inscritos.cve_alumno AND calificacion_parcial.cve_materia = ai_inscritos.cve_materia_academica AND calificacion_parcial.cve_grupo = ai_inscritos.cve_grupo_academica INNER JOIN ai_grupos ON ai_inscritos.cve_grupo = ai_grupos.cve_grupo WHERE  (ai_inscritos.cve_grupo = " + this.cve_grupo + ") AND (calificacion_parcial.cve_parcial >= 111) AND (calificacion_parcial.cve_parcial <= 333)";
         this.MBD.insertarSQL(this.StrConsultas);
         this.StrConsultas = "UPDATE calificacionez_alumno SET calificacionez_alumno.cve_maestro = ai_grupos.cve_maestro_comple FROM ai_inscritos INNER JOIN ai_grupos ON ai_inscritos.cve_grupo = ai_grupos.cve_grupo INNER JOIN calificacionez_alumno ON ai_inscritos.cve_alumno = calificacionez_alumno.cve_alumno AND ai_inscritos.cve_grupo_academica = calificacionez_alumno.cve_grupo AND ai_inscritos.cve_materia_academica = calificacionez_alumno.cve_materia WHERE (ai_inscritos.cve_grupo = " + this.cve_grupo + ") and (calificacionez_alumno.opcion_calif = 2)";
         this.MBD.insertarSQL(this.StrConsultas);
         this.AGAI.encabezado = "Asignacion Registro Calificaciones complementarias ";
         this.mensaje = "Estimada(o) docente <br><br> Reciba un cordial saludo, por medio del presente, me permito solicitar su valioso apoyo para la captura de calificaciones de los estudiantes en la evaluaci\u00f3n de Acciones Complementarias de Regularizaci\u00f3n <label> <i style='color: #007FA6'> Ingles </i> </label>, en el sistema institucional (SIISC). <br><br> Su colaboraci\u00f3n es fundamental para asegurar que este proceso se lleve a cabo de manera eficiente dentro de las fechas establecidas, contribuyendo al cierre adecuado del periodo acad\u00e9mico. <br> <br> En caso de tener alguna duda sobre el procedimiento, no duden en comunicarse con su Director de Divisi\u00f3n. <br><br> Agradecemos sinceramente su compromiso con la calidad educativa y el trabajo colaborativo que caracteriza a nuestra comunidad docente. <br><br> A T E N T A M E N T E <br>SISTEMA INTEGRAL DE LA INFORMACI&Oacute;N DEL SISTEMA DE CALIDAD <br> Direcci\u00f3n de Divisi\u00f3n <br> <i> Departamento de Tecnolog&iacute;as de Informaci&oacute;n </i>";
         this.AGAI.envio_general(this.cve_profesor_comple, this.mensaje, 2);
         this.mensaje = "Confirmacion de docente (Complementarias)";
      }

      if (this.cve_profesor_acciones > 0) {
         this.StrConsultas = "UPDATE ai_grupos SET cve_maestro_accionez = " + this.cve_profesor_acciones + " WHERE (cve_grupo = " + this.cve_grupo + ") AND (fecha_firma_accionez IS NULL) ";
         this.MBD.insertarSQL(this.StrConsultas);
         this.StrConsultas = "UPDATE calificacion_parcial SET calificacion_parcial.cve_maestro = ai_grupos.cve_maestro_accionez FROM  calificacion_parcial INNER JOIN ai_inscritos ON calificacion_parcial.cve_alumno = ai_inscritos.cve_alumno AND calificacion_parcial.cve_materia = ai_inscritos.cve_materia_academica AND calificacion_parcial.cve_grupo = ai_inscritos.cve_grupo_academica INNER JOIN ai_grupos ON ai_inscritos.cve_grupo = ai_grupos.cve_grupo WHERE  (ai_inscritos.cve_grupo = " + this.cve_grupo + ") AND (calificacion_parcial.cve_parcial = 4) ";
         this.MBD.insertarSQL(this.StrConsultas);
         this.StrConsultas = "UPDATE calificacionez_alumno SET calificacionez_alumno.cve_maestro = ai_grupos.cve_maestro_accionez FROM ai_inscritos INNER JOIN ai_grupos ON ai_inscritos.cve_grupo = ai_grupos.cve_grupo INNER JOIN calificacionez_alumno ON ai_inscritos.cve_alumno = calificacionez_alumno.cve_alumno AND ai_inscritos.cve_grupo_academica = calificacionez_alumno.cve_grupo AND ai_inscritos.cve_materia_academica = calificacionez_alumno.cve_materia WHERE (ai_inscritos.cve_grupo = " + this.cve_grupo + ") and (calificacionez_alumno.opcion_calif = 3)";
         this.MBD.insertarSQL(this.StrConsultas);
         this.AGAI.encabezado = "Asignacion Registro Calificaciones Acciones Especiales ";
         this.mensaje = "Estimada(o) docente <br><br> Reciba un cordial saludo, por medio del presente, me permito solicitar su valioso apoyo para la captura de calificaciones de los estudiantes en la evaluaci\u00f3n de Acciones Especiales de Regularizaci\u00f3n de <label> <i style='color: #007FA6'> Ingles </i> </label>, en el sistema institucional (SIISC). <br><br> Su colaboraci\u00f3n es fundamental para asegurar que este proceso se lleve a cabo de manera eficiente dentro de las fechas establecidas, contribuyendo al cierre adecuado del periodo acad\u00e9mico. <br> <br> En caso de tener alguna duda sobre el procedimiento, no duden en comunicarse con su Director de Divisi\u00f3n. <br><br> Agradecemos sinceramente su compromiso con la calidad educativa y el trabajo colaborativo que caracteriza a nuestra comunidad docente. <br><br> A T E N T A M E N T E <br>SISTEMA INTEGRAL DE LA INFORMACI&Oacute;N DEL SISTEMA DE CALIDAD <br> Direcci\u00f3n de Divisi\u00f3n <br> <i> Departamento de Tecnolog&iacute;as de Informaci&oacute;n </i>";
         this.AGAI.envio_general(this.cve_profesor_acciones, this.mensaje, 2);
      }

   }

   public void elimina_grupo() throws Exception {
      this.StrConsultas = "SELECT COUNT (cve_grupo) AS maximo FROM ai_inscritos WHERE (cve_grupo = " + this.cve_grupo + ") ";
      this.cuantos = this.MBD.buscaSQL(this.StrConsultas);
      if (this.cuantos == 0) {
         this.StrConsultas = "DELETE FROM ai_grupos WHERE (cve_grupo = " + this.cve_grupo + ") ";
         this.MBD.insertarSQL(this.StrConsultas);
         this.StrConsultas = "DELETE FROM ai_horarios_clase WHERE (cve_grupo = " + this.cve_grupo + ") ";
         this.MBD.insertarSQL(this.StrConsultas);
         this.StrConsultas = "DELETE FROM  ai_materiaz_planeazion_impartizion WHERE (cve_grupo = " + this.cve_grupo + ") ";
         this.MBD.insertarSQL(this.StrConsultas);
         this.StrConsultas = "DELETE FROM  ai_materiaz_planeazion_profezor WHERE (cve_grupo = " + this.cve_grupo + ") ";
         this.MBD.insertarSQL(this.StrConsultas);
         this.error = "ELIMINACION DEL GRUPO";
      } else {
         this.error = "EXISTEN ALUMNOS EN EL GRUPO";
      }

   }

   public void busca_grupo() throws Exception {
      this.StrConsultas = "SELECT ai_grupos.cve_grupo, ai_grupos.cve_periodo, ai_grupos.cve_maestro, ai_grupos.nombre,  ai_grupos.cve_nivel, ai_grupos.grado_academico, cve_maestro_comple, cve_maestro_accionez, ISNULL( CONVERT(VARCHAR(24), fecha_firma_ordinaria, 103) , '--/--/--' ) AS fecha_firma_ordinaria, ISNULL( CONVERT(VARCHAR(24), fecha_firma_comple, 103) , '--/--/--' ) AS fecha_firma_comple, ISNULL( CONVERT(VARCHAR(24), fecha_firma_accionez, 103) , '--/--/--' ) AS fecha_firma_accionez FROM ai_grupos INNER JOIN ai_cat_nivel ON ai_grupos.cve_nivel = ai_cat_nivel.cve_nivel INNER JOIN periodos ON ai_grupos.cve_periodo = periodos.cve_periodo WHERE (ai_grupos.cve_grupo =" + this.cve_grupo + ") ";

      for(this.rs = this.MBD.SQLBD(this.StrConsultas); this.rs.next(); this.fecha_acciones = this.rs.getString(11)) {
         this.cve_grupo = this.rs.getInt(1);
         this.cve_periodo = this.rs.getInt(2);
         this.cve_profesor = this.rs.getInt(3);
         this.nombre_grupo = this.rs.getString(4);
         this.cve_nivel = this.rs.getInt(5);
         this.grado_academico = this.rs.getInt(6);
         this.cve_profesor_comple = this.rs.getInt(7);
         this.cve_profesor_acciones = this.rs.getInt(8);
         this.fecha_ordinaria = this.rs.getString(9);
         this.fecha_comple = this.rs.getString(10);
      }

      this.MBD.desconectarBD();
   }

   public void Envio() throws Exception {
      this.StrConsultas = "SELECT CASE numero_periodo WHEN 1 THEN 'SEP-DIC ' + CONVERT(VARCHAR(4), ano) WHEN 2 THEN 'ENE-ABR ' + CONVERT(VARCHAR(4), ano) WHEN 3 THEN 'MAY-AGO ' + CONVERT(VARCHAR(4), ano) END AS Periodo, ai_grupos.nombre FROM periodos INNER JOIN ai_grupos ON periodos.cve_periodo = ai_grupos.cve_periodo WHERE (ai_grupos.cve_grupo =" + this.cve_grupo + ")";

      for(this.rs = this.MBD.SQLBD(this.StrConsultas); this.rs.next(); this.nombre_grupo = this.rs.getString(2)) {
         this.periodo = this.rs.getString(1);
      }

      this.MBD.desconectarBD();
      this.StrConsultas = "SELECT cve_maestro FROM ai_grupos WHERE (cve_periodo = " + this.cve_periodo + ")";
      this.rs = this.MBD.SQLBD(this.StrConsultas);

      while(this.rs.next()) {
         this.cves_maestros = this.rs.getInt(1);
         this.AGAI.encabezado = "Asignacion de grupo de idiomas";
         this.mensaje = "Buen@s dias/tardes estimad@ docente, por medio de la presente se le comunica que se le ha asignado un grupo como parte de la academia de idiomas <br> Nombre del Grupo: " + this.nombre_grupo + " <br> Cuatrimestre: " + this.periodo + " <br> Para la impartici&oacute;n de clases y dar seguimiento del mismo <br> A T E N T A M E N T E <br> Sistema Integral de la Informaci&oacute;n del Sistema de Calidad <br> Coordinaci&oacute;n de idiomas <br> <i> Departamento de Tecnolog&iacute;as de Informaci&oacute;n </i>";
         this.AGAI.envio_general(this.cves_maestros, this.mensaje);
      }

      this.MBD.desconectarBD();
      this.error = "Su Notificaci\u00f3n se env\u00edo con \u00e9xito";
   }

   public static void main(String[] args) throws Exception {
      System.out.println("24/03/2019   Neftali Cruz  Actualizacion del docente en calificaciones");
      System.out.println("29/09/2022   Nefta  Actualizacion  en la eliminacion del grupo");
      System.out.println("06/08/2025   Nefta  Campos nuevos, para considerar el cambio de profesores en niveles, actas complementarias");
      System.out.println("04/09/2025   Nefta  Activacion de correos, para notificar docentes en ingles");
   }
}
